### ISSUE TITLE
Mise à jour des demo

### ISSUE THREAD

**Issue by 60662** [dotnet/AspNetCore.Docs.fr-fr#242]
Serait il possible d'avoir une mise à jours  des dépôts pour la version correspondant au framwork  ou d'avoir directement les source des page d authentification pour pouvoir faire évoluer l application sans  tout développer 
Jpp

---
#### Détails du document

⚠ *Ne pas modifier cette section. C’est obligatoire pour docs.microsoft.com ➟ Liaison des problèmes GitHub.*

* ID: 393b3379-6061-50a4-0975-b3d1d82b660b
* Version Independent ID: 48e4e204-ea22-c225-0cbc-0d811bdb90ed
* Content: [Vue d’ensemble de l’authentification ASP.NET Core](https://docs.microsoft.com/fr-fr/aspnet/core/security/authentication/?view=aspnetcore-3.1#feedback)
* Content Source: [aspnetcore/security/authentication/index.md](https://github.com/dotnet/AspNetCore.Docs.fr-fr/blob/live/aspnetcore/security/authentication/index.md)
* Product: **aspnet-core**
* Technology: **aspnetcore-security**
* GitHub Login: @mjrousos
* Microsoft Alias: **riande**

**Comment by srvbpigh** [comment]
Hello, @60662
 
Thank you for your feedback.
 
We are actively reviewing your comments and will get back to you soon.


Kind regards,
Microsoft DOCS International Team

**Comment by V-vafune** [comment]
Bonjour @60662 ,  

Merci pour votre contribution. Notre équipe peut uniquement répondre au feedback qui porte sur la documentation.  

Pour envoyer vos commentaires produit, nous vous invitons à cliquer sur le bouton « Envoyer des commentaires sur le produit » situé au bas de la page Docs.  

Si vous avez des commentaires sur la documentation, n’hésitez pas à nous les envoyer via ce canal.  

Votre contribution à nos articles est grandement appréciée.   

Cordialement,  

L’équipe Microsoft DOCS International
