### ISSUE TITLE
The rendering of the document has some :::no-loc(Blazor):::! :and ::no-loc(Blazor Server):::

### ISSUE THREAD

**Issue by AClerbois** [dotnet/AspNetCore.Docs.fr-fr#261]
The rendering of the document has some :::no-loc(Blazor):::! :and ::no-loc(Blazor Server):::

---
#### Détails du document

⚠ *Ne pas modifier cette section. C’est obligatoire pour docs.microsoft.com ➟ Liaison des problèmes GitHub.*

* ID: 5bc28995-6784-a7d2-5c0b-9811a8d19c1a
* Version Independent ID: 1668c8fb-024c-c86d-d4d5-e22e3355c04b
* Content: [Présentation de ASP.NET Core :::no-loc(Blazor):::](https://docs.microsoft.com/fr-fr/aspnet/core/blazor/?view=aspnetcore-3.1)
* Content Source: [aspnetcore/blazor/index.md](https://github.com/dotnet/AspNetCore.Docs.fr-fr/blob/live/aspnetcore/blazor/index.md)
* Product: **aspnet-core**
* Technology: **aspnetcore-blazor**
* GitHub Login: @guardrex
* Microsoft Alias: **riande**

**Comment by guardrex** [comment]
Hello @AClerbois ... It's a known issue that the doc engineers are working on.

cc: @JasonCard

**Comment by AClerbois** [comment]
Ok good to know, if the issue is known, we can close mine to avoid too many same issue.
